### ISSUE TITLE
多标签图片

### ISSUE THREAD

**Issue by lzl2040** [OysterQAQ/ACG2vec#2]
请问如何对多标签图片进行推断呢

**Comment by OysterQAQ** [comment]
是要进行图片到标签的推断？一般的做法有两种：
1如果你的数据有人工标注的数据 可以自己构建多标签多类的分类任务 在自己的数据上预训练完之后 用于同场景的图片推断
2是使用诸如clip之类的多模态模型 如果是动漫插图领域可以使用本repo的dlip ，首先需要有预设好的标签库，标签库需要使用dlip将所有标签抽取成768维向量，将（标签id，标签向量）存入向量检索引擎（类似milvus）中 。之后将待生成标签的图片使用dlip编码成768维图片特征向量，在向量检索引擎中检索，利用向量距离指标，引擎会给出最近似的文本标签id列表，根据需要选取其中的标签id

**Comment by lzl2040** [comment]
我是想使用clip模型在多标签数据集上进行微调，训练的过程大致清楚，但是推断的时候不清楚该怎么得到匹配的标签，是最后使用topk吗

**Comment by OysterQAQ** [comment]
是的
